Traceback (most recent call last):
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/app.py", line 1, in <module>
    from flask import Flask, json, redirect, render_template, url_for, request, flash, make_response, session, jsonify
ModuleNotFoundError: No module named 'flask'
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ python app.py
Orden «python» no encontrada. Quizá quiso decir:
  la orden «python3» del paquete deb «python3»
  la orden «python» del paquete deb «python-is-python3»
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ cd ..
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend$ pip install -r requirements.txt
Collecting click==8.0.1
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Requirement already satisfied: colorama==0.4.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.4.4)
Collecting Flask==2.0.1
  Using cached Flask-2.0.1-py3-none-any.whl (94 kB)
Collecting Flask-Cors==3.0.10
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting flask-marshmallow==0.14.0
  Downloading flask_marshmallow-0.14.0-py2.py3-none-any.whl (10 kB)
Collecting Flask-SQLAlchemy==2.5.1
  Using cached Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
Collecting greenlet==1.1.1
  Downloading greenlet-1.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
     |████████████████████████████████| 147 kB 960 kB/s 
Collecting itsdangerous==2.0.1
  Using cached itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting Jinja2==3.0.1
  Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting MarkupSafe==2.0.1
  Using cached MarkupSafe-2.0.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Collecting marshmallow==3.13.0
  Downloading marshmallow-3.13.0-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 253 kB/s 
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting SQLAlchemy==1.4.23
  Downloading SQLAlchemy-1.4.23-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 1.1 MB/s 
Collecting Werkzeug==2.0.1
  Using cached Werkzeug-2.0.1-py3-none-any.whl (288 kB)
Installing collected packages: MarkupSafe, Werkzeug, Jinja2, itsdangerous, greenlet, click, SQLAlchemy, six, marshmallow, Flask, Flask-SQLAlchemy, flask-marshmallow, Flask-Cors
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
Successfully installed Flask-2.0.1 Flask-Cors-3.0.10 Flask-SQLAlchemy-2.5.1 Jinja2-3.0.1 MarkupSafe-2.0.1 SQLAlchemy-1.4.23 Werkzeug-2.0.1 click-8.0.1 flask-marshmallow-0.14.0 greenlet-1.1.1 itsdangerous-2.0.1 marshmallow-3.13.0 six-1.16.0
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend$ cd src
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ python3 app.py
Traceback (most recent call last):
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/app.py", line 2, in <module>
    from sql import Event, Presentation, User, Role, Nationality, LocalGroup, app, db
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/sql.py", line 14, in <module>
    db.create_all()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 167, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ python3 app.py
Traceback (most recent call last):
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/app.py", line 2, in <module>
    from sql import Event, Presentation, User, Role, Nationality, LocalGroup, app, db
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/sql.py", line 15, in <module>
    db.create_all()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 167, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ pip install pymysql
Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 623 kB/s 
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ python3 app.py
Traceback (most recent call last):
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/app.py", line 2, in <module>
    from sql import Event, Presentation, User, Role, Nationality, LocalGroup, app, db
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/sql.py", line 15, in <module>
    db.create_all()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 167, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ ^C
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ pip install mysql-connector-python
Collecting mysql-connector-python
  Downloading mysql_connector_python-8.0.26-cp39-cp39-manylinux1_x86_64.whl (30.9 MB)
     |████████████████████████████████| 30.9 MB 73 kB/s 
Collecting protobuf>=3.0.0
  Downloading protobuf-3.18.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 4.1 MB/s 
Installing collected packages: protobuf, mysql-connector-python
Successfully installed mysql-connector-python-8.0.26 protobuf-3.18.0
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ python3 app.py
Traceback (most recent call last):
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/app.py", line 2, in <module>
    from sql import Event, Presentation, User, Role, Nationality, LocalGroup, app, db
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/sql.py", line 15, in <module>
    db.create_all()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 167, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ python3 app.py
Traceback (most recent call last):
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/app.py", line 2, in <module>
    from sql import Event, Presentation, User, Role, Nationality, LocalGroup, app, db
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/sql.py", line 15, in <module>
    db.create_all()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 167, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ pip3 install mysqlclient
Collecting mysqlclient
  Downloading mysqlclient-2.0.3.tar.gz (88 kB)
     |████████████████████████████████| 88 kB 471 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_f16517cea77b42d0a32df58424812857/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_f16517cea77b42d0a32df58424812857/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_1d7jzke
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_f16517cea77b42d0a32df58424812857/
    Complete output (15 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f16517cea77b42d0a32df58424812857/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f16517cea77b42d0a32df58424812857/setup_posix.py", line 70, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f16517cea77b42d0a32df58424812857/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    mysql_config --version
    mariadb_config --version
    mysql_config --libs
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3c/df/59cd2fa5e48d0804d213bdcb1acb4d08c403b61c7ff7ed4dd4a6a2deb3f7/mysqlclient-2.0.3.tar.gz#sha256=f6ebea7c008f155baeefe16c56cd3ee6239f7a5a9ae42396c2f1860f08a7c432 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-2.0.2.tar.gz (88 kB)
     |████████████████████████████████| 88 kB 1.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_62c49da1c7f84484928b1200497eae79/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_62c49da1c7f84484928b1200497eae79/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_1swcpwj
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_62c49da1c7f84484928b1200497eae79/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_62c49da1c7f84484928b1200497eae79/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_62c49da1c7f84484928b1200497eae79/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_62c49da1c7f84484928b1200497eae79/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0e/68/f79de0e0fcdb041783124b825771e0ba6a3d0893b7b4c4735f130e42af47/mysqlclient-2.0.2.tar.gz#sha256=8df057b08fc27d8f7106bfa997d0a21e2acef017f905f06d6fb0aa6a20d4d2b2 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-2.0.1.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 2.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_f1eb028593ae4429a8b755a56aad0146/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_f1eb028593ae4429a8b755a56aad0146/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jcrxi5_3
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_f1eb028593ae4429a8b755a56aad0146/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f1eb028593ae4429a8b755a56aad0146/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f1eb028593ae4429a8b755a56aad0146/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f1eb028593ae4429a8b755a56aad0146/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a5/e1/e5f2b231c05dc51d9d87fa5066f90d1405345c54b14b0b11a1c859020f21/mysqlclient-2.0.1.tar.gz#sha256=fb2f75aea14722390d2d8ddf384ad99da708c707a96656210a7be8af20a2c5e5 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-2.0.0.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 2.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_f8fe5eb0f6564dfb8dc2ccf40d4d4a46/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_f8fe5eb0f6564dfb8dc2ccf40d4d4a46/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-frugxl_b
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_f8fe5eb0f6564dfb8dc2ccf40d4d4a46/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f8fe5eb0f6564dfb8dc2ccf40d4d4a46/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f8fe5eb0f6564dfb8dc2ccf40d4d4a46/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f8fe5eb0f6564dfb8dc2ccf40d4d4a46/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ca/cf/dd8124bf8b3d2ae465db9c8ce35c51650c31784b095f41faf6f8cad987a0/mysqlclient-2.0.0.tar.gz#sha256=201dfcc2a3c8a0859ea399947f1af8abe74b706beba0ebac149180d9d7b0f6e8 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.4.6.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 1.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_30b9a6214df746f7b3f0e37bb9f4db7b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_30b9a6214df746f7b3f0e37bb9f4db7b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q173_imj
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_30b9a6214df746f7b3f0e37bb9f4db7b/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_30b9a6214df746f7b3f0e37bb9f4db7b/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_30b9a6214df746f7b3f0e37bb9f4db7b/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_30b9a6214df746f7b3f0e37bb9f4db7b/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz#sha256=f3fdaa9a38752a3b214a6fe79d7cae3653731a53e577821f9187e67cbecb2e16 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.4.5.tar.gz (86 kB)
     |████████████████████████████████| 86 kB 2.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_2708ec21f25e481f83b59d70244054b6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_2708ec21f25e481f83b59d70244054b6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-akkdxaxe
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_2708ec21f25e481f83b59d70244054b6/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_2708ec21f25e481f83b59d70244054b6/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_2708ec21f25e481f83b59d70244054b6/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_2708ec21f25e481f83b59d70244054b6/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f8/9b/5db9a03e2088a87c26e3e4d4c7f7e8f4c2dbae610f9521cdfac15755a795/mysqlclient-1.4.5.tar.gz#sha256=e80109b0ae8d952b900b31b623181532e5e89376d707dcbeb63f99e69cefe559 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.4.4.tar.gz (86 kB)
     |████████████████████████████████| 86 kB 2.2 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_0030699666b54e459786eb8e68d50fc2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_0030699666b54e459786eb8e68d50fc2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mld5x27a
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_0030699666b54e459786eb8e68d50fc2/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_0030699666b54e459786eb8e68d50fc2/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_0030699666b54e459786eb8e68d50fc2/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_0030699666b54e459786eb8e68d50fc2/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4d/38/c5f8bac9c50f3042c8f05615f84206f77f03db79781db841898fde1bb284/mysqlclient-1.4.4.tar.gz#sha256=9c737cc55a5dc8dd3583a942d5a9b21be58d16f00f5fefca4e575e7d9682e98c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.4.3.tar.gz (86 kB)
     |████████████████████████████████| 86 kB 2.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_6a71f49c334b4b13a4bd1393ca8da34a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_6a71f49c334b4b13a4bd1393ca8da34a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ype8rdas
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_6a71f49c334b4b13a4bd1393ca8da34a/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_6a71f49c334b4b13a4bd1393ca8da34a/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_6a71f49c334b4b13a4bd1393ca8da34a/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_6a71f49c334b4b13a4bd1393ca8da34a/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/13/37/6c941aabeb78464a538b7d43266bfae645993779e3ca3e12fe82b4590f52/mysqlclient-1.4.3.tar.gz#sha256=0d3eeb97534c9f42e9b65bd35c1a35fadc2f6d7ea5d9fdbda5339a569156344b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.4.2.post1.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 2.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_27cac0c4e3f3459ebf8bc4519e8ac8e1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_27cac0c4e3f3459ebf8bc4519e8ac8e1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-j2k2kndx
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_27cac0c4e3f3459ebf8bc4519e8ac8e1/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_27cac0c4e3f3459ebf8bc4519e8ac8e1/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_27cac0c4e3f3459ebf8bc4519e8ac8e1/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_27cac0c4e3f3459ebf8bc4519e8ac8e1/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz#sha256=f257d250f2675d0ef99bd318906f3cfc05cef4a2f385ea695ff32a3f04b9f9a7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.4.2.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 1.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_ed81b5fa28d342b3a3da7618d0f6425e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_ed81b5fa28d342b3a3da7618d0f6425e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ko2m2s04
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_ed81b5fa28d342b3a3da7618d0f6425e/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_ed81b5fa28d342b3a3da7618d0f6425e/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_ed81b5fa28d342b3a3da7618d0f6425e/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_ed81b5fa28d342b3a3da7618d0f6425e/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/73/79/67ddf24ac31b05d741f0ac87fa612c7a11bab1b39b8270ed7344d149f8af/mysqlclient-1.4.2.tar.gz#sha256=b95edaa41d6cc47deecabcdcbb5ab437ad9ae6d8955f5cf10d1847b37e66ef5e (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.4.1.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 2.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_d4af94aa9bbf46659ec871028c795ed4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_d4af94aa9bbf46659ec871028c795ed4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5wn3_id6
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_d4af94aa9bbf46659ec871028c795ed4/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_d4af94aa9bbf46659ec871028c795ed4/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_d4af94aa9bbf46659ec871028c795ed4/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_d4af94aa9bbf46659ec871028c795ed4/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/de/d7/919042fb7ed78a89e21c4e43d5daed90d5df18ec183bae3de493a7d9e3ed/mysqlclient-1.4.1.tar.gz#sha256=a62220410e26ce2d2ff94dd0138c3ecfb91db634464a9afb4c8e6b50f0a67e00 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.4.0.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 1.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_4d24c9d9bdc14a9d9a0ecbc94658544a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_4d24c9d9bdc14a9d9a0ecbc94658544a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4jrkxnyn
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_4d24c9d9bdc14a9d9a0ecbc94658544a/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_4d24c9d9bdc14a9d9a0ecbc94658544a/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_4d24c9d9bdc14a9d9a0ecbc94658544a/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_4d24c9d9bdc14a9d9a0ecbc94658544a/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/05/73/fac741eef89b0257fb1807de80e96474f40d52739cdbc32c90c4a793e79d/mysqlclient-1.4.0.tar.gz#sha256=efeaacd04feea7d44fef2a5adf4df335b438458f8b89144307dc5a90025761a5 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.14.tar.gz (91 kB)
     |████████████████████████████████| 91 kB 2.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_22d72d5aaf97496095a529eb39a6a79b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_22d72d5aaf97496095a529eb39a6a79b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6lk3eryw
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_22d72d5aaf97496095a529eb39a6a79b/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_22d72d5aaf97496095a529eb39a6a79b/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_22d72d5aaf97496095a529eb39a6a79b/setup_posix.py", line 53, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_22d72d5aaf97496095a529eb39a6a79b/setup_posix.py", line 28, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f7/a2/1230ebbb4b91f42ad6b646e59eb8855559817ad5505d81c1ca2b5a216040/mysqlclient-1.3.14.tar.gz#sha256=3981ae9ce545901a36a8b7aed76ed02960a429f75dc53b7ad77fb2f9ab7cd56b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.13.tar.gz (90 kB)
     |████████████████████████████████| 90 kB 2.8 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_ceffd4131a95439097b0a2e57350f68d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_ceffd4131a95439097b0a2e57350f68d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zdo7i2sn
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_ceffd4131a95439097b0a2e57350f68d/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_ceffd4131a95439097b0a2e57350f68d/setup.py", line 18, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_ceffd4131a95439097b0a2e57350f68d/setup_posix.py", line 53, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_ceffd4131a95439097b0a2e57350f68d/setup_posix.py", line 28, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz#sha256=ff8ee1be84215e6c30a746b728c41eb0701a46ca76e343af445b35ce6250644f (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.12.tar.gz (89 kB)
     |████████████████████████████████| 89 kB 2.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_61e86188ceb548099772bf1fa3aaa978/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_61e86188ceb548099772bf1fa3aaa978/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-r08pwo5x
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_61e86188ceb548099772bf1fa3aaa978/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_61e86188ceb548099772bf1fa3aaa978/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_61e86188ceb548099772bf1fa3aaa978/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_61e86188ceb548099772bf1fa3aaa978/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz#sha256=2d9ec33de39f4d9c64ad7322ede0521d85829ce36a76f9dd3d6ab76a9c8648e5 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.11.tar.gz (89 kB)
     |████████████████████████████████| 89 kB 2.5 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_79caed6af3c44e8083cdeba20a4ce497/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_79caed6af3c44e8083cdeba20a4ce497/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-icgfvxiy
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_79caed6af3c44e8083cdeba20a4ce497/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_79caed6af3c44e8083cdeba20a4ce497/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_79caed6af3c44e8083cdeba20a4ce497/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_79caed6af3c44e8083cdeba20a4ce497/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6a/4d/856d1848e9b7fa8577a31c0188592f472e5cbc94f588c2a40ff930533d73/mysqlclient-1.3.11.tar.gz#sha256=9a79b38843d61f651266ff16b9fdcc8830d21f0fb852e4406a19e9a715bdf3e2 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.10.tar.gz (82 kB)
     |████████████████████████████████| 82 kB 180 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_89fa5b9c7444422cac95154a5ef66447/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_89fa5b9c7444422cac95154a5ef66447/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k7rtlmba
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_89fa5b9c7444422cac95154a5ef66447/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_89fa5b9c7444422cac95154a5ef66447/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_89fa5b9c7444422cac95154a5ef66447/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_89fa5b9c7444422cac95154a5ef66447/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/9b/0bc869f290b8f49a99b8d97927f57126a5d1befcf8bac92c60dc855f2523/mysqlclient-1.3.10.tar.gz#sha256=452aaf9d2ba1a4fb85c134c88f9b1857852deed63b3b13255d7a65d2c1297262 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.9.tar.gz (81 kB)
     |████████████████████████████████| 81 kB 2.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_2adad7faca4a46d0b023d818261ccbfa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_2adad7faca4a46d0b023d818261ccbfa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-c5e5l705
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_2adad7faca4a46d0b023d818261ccbfa/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_2adad7faca4a46d0b023d818261ccbfa/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_2adad7faca4a46d0b023d818261ccbfa/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_2adad7faca4a46d0b023d818261ccbfa/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/db/f5/c8e1657985c31dda16e434edf5257c31572fa5faacd7e48b1618390e4b18/mysqlclient-1.3.9.tar.gz#sha256=990ccf1e1f15b9a291b811c993dc1c216566714bc14e6581b38665bd61c28c99 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.8.tar.gz (81 kB)
     |████████████████████████████████| 81 kB 2.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_aa184d11c7d84bbf95efc4a6fb5163f8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_aa184d11c7d84bbf95efc4a6fb5163f8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e7mbque9
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_aa184d11c7d84bbf95efc4a6fb5163f8/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_aa184d11c7d84bbf95efc4a6fb5163f8/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_aa184d11c7d84bbf95efc4a6fb5163f8/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_aa184d11c7d84bbf95efc4a6fb5163f8/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/31/ce/7ea049b3d5929b3cce3104967ccca218a9f054517f0d15dfdaf4e76da2a0/mysqlclient-1.3.8.tar.gz#sha256=c64bc386c0b771ed6ff76de0f52e0f957f98d9e13c83b0ddb821afdbe3f5d970 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.7.tar.gz (79 kB)
     |████████████████████████████████| 79 kB 2.5 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_44a36d3b9ace454dabd288d2abdd88a1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_44a36d3b9ace454dabd288d2abdd88a1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qn2frdji
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_44a36d3b9ace454dabd288d2abdd88a1/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_44a36d3b9ace454dabd288d2abdd88a1/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_44a36d3b9ace454dabd288d2abdd88a1/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_44a36d3b9ace454dabd288d2abdd88a1/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/74/ff/4e964e20b559e55d7afa60fbccc6a560f2adf289813bd3d7eb4eb8a87093/mysqlclient-1.3.7.tar.gz#sha256=c74a83b4cb2933d0e43370117eeebdfa03077ae72686d2df43d31879267f1f1b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.6.tar.gz (78 kB)
     |████████████████████████████████| 78 kB 2.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_a84cb13e57114497a52efda02849ffa0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_a84cb13e57114497a52efda02849ffa0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pzv5dla4
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_a84cb13e57114497a52efda02849ffa0/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_a84cb13e57114497a52efda02849ffa0/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_a84cb13e57114497a52efda02849ffa0/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_a84cb13e57114497a52efda02849ffa0/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/09/29/6648563af4b45798ba667f17ea55166d7b0ed8717937c06977a1fdbe7df6/mysqlclient-1.3.6.tar.gz#sha256=1f63a8ab111530a0ff9acaeb118074f11e7564b7c124f2e7fc56fcac641aecf2 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.5.tar.gz (77 kB)
     |████████████████████████████████| 77 kB 2.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_88b74fedf132422c9e3c69a64b6f623e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_88b74fedf132422c9e3c69a64b6f623e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1zcsbo_d
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_88b74fedf132422c9e3c69a64b6f623e/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_88b74fedf132422c9e3c69a64b6f623e/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_88b74fedf132422c9e3c69a64b6f623e/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_88b74fedf132422c9e3c69a64b6f623e/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/82/ea/336daf6c7baa564d0c434ab748218d1a7dc61dfc7066e98b72afd24fd2b9/mysqlclient-1.3.5.tar.gz#sha256=80ea68f6f3c2cfbf35c91adde2b40de1f2c31132118d2dcee048c72423f678bf (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.4.tar.gz (77 kB)
     |████████████████████████████████| 77 kB 1.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_117b7f8e8a704fac80cdf5ded7bd5979/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_117b7f8e8a704fac80cdf5ded7bd5979/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2axzmlxr
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_117b7f8e8a704fac80cdf5ded7bd5979/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_117b7f8e8a704fac80cdf5ded7bd5979/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_117b7f8e8a704fac80cdf5ded7bd5979/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_117b7f8e8a704fac80cdf5ded7bd5979/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/17/d9/03b08e6a033401335b720806b87596aee8d7f7aa87539713238905c4a8d1/mysqlclient-1.3.4.tar.gz#sha256=a0263383f8ac33ad12d68dc61fa8ccbee41244ce916287c6cee71bf8aea82c5c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.3.tar.gz (77 kB)
     |████████████████████████████████| 77 kB 2.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_6b83246f0b6241328ef7c75f9e99cf4b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_6b83246f0b6241328ef7c75f9e99cf4b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lc4ulkdt
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_6b83246f0b6241328ef7c75f9e99cf4b/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_6b83246f0b6241328ef7c75f9e99cf4b/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_6b83246f0b6241328ef7c75f9e99cf4b/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_6b83246f0b6241328ef7c75f9e99cf4b/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/26/53/c575db342bfca0213c9243ed2642bfadcd420b18d2f477dc812543e3d83a/mysqlclient-1.3.3.tar.gz#sha256=0f0887882d71bf2a079d9724d9323053cfbee8ab2dcfc989daf97d7ce5be9af9 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.2.tar.gz (77 kB)
     |████████████████████████████████| 77 kB 1.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_8a076e126f4040c4bea1d9d91ca4f18a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_8a076e126f4040c4bea1d9d91ca4f18a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-266hwq8s
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_8a076e126f4040c4bea1d9d91ca4f18a/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_8a076e126f4040c4bea1d9d91ca4f18a/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_8a076e126f4040c4bea1d9d91ca4f18a/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_8a076e126f4040c4bea1d9d91ca4f18a/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2d/df/5440ee86bbb248325cdd6e1fc9cbbba365018a0d2d57f673610e020e6b1d/mysqlclient-1.3.2.tar.gz#sha256=e44025830501b9f70f8c2fe8eeff66f0df2df198802f7295801dac199b8236ef (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.1.tar.gz (76 kB)
     |████████████████████████████████| 76 kB 2.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_f29373344c87448c8cfa451236099560/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_f29373344c87448c8cfa451236099560/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e5aptdcf
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_f29373344c87448c8cfa451236099560/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f29373344c87448c8cfa451236099560/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f29373344c87448c8cfa451236099560/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_f29373344c87448c8cfa451236099560/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6b/ba/4729d99e85a0a35bb46d55500570de05b4af10431cef174b6da9f58a0e50/mysqlclient-1.3.1.tar.gz#sha256=3549e8a61f10c8cd8eac6581d3f44d0594f535fb7b29e6090db3a0bc547b25ad (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.0.tar.gz (76 kB)
     |████████████████████████████████| 76 kB 2.2 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttblmy5g/mysqlclient_6ca8a191964348d7ba5bfd6dd09a7164/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttblmy5g/mysqlclient_6ca8a191964348d7ba5bfd6dd09a7164/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3l3ieegs
         cwd: /tmp/pip-install-ttblmy5g/mysqlclient_6ca8a191964348d7ba5bfd6dd09a7164/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttblmy5g/mysqlclient_6ca8a191964348d7ba5bfd6dd09a7164/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-ttblmy5g/mysqlclient_6ca8a191964348d7ba5bfd6dd09a7164/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-ttblmy5g/mysqlclient_6ca8a191964348d7ba5bfd6dd09a7164/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6a/91/bdfe808fb5dc99a5f65833b370818161b77ef6d1e19b488e4c146ab615aa/mysqlclient-1.3.0.tar.gz#sha256=06eb5664e3738b283ea2262ee60ed83192e898f019cc7ff251f4d05a564ab3b7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement mysqlclient
ERROR: No matching distribution found for mysqlclient
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ ^C
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ python3 app.py
Traceback (most recent call last):
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/app.py", line 2, in <module>
    from sql import Event, Presentation, User, Role, Nationality, LocalGroup, app, db
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/sql.py", line 15, in <module>
    db.create_all()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 167, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ python3 app.py
Traceback (most recent call last):
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/app.py", line 2, in <module>
    from sql import Event, Presentation, User, Role, Nationality, LocalGroup, app, db
  File "/home/sebastian/Documentos/Cyber-Link_GBU_2022/Backend/src/sql.py", line 15, in <module>
    db.create_all()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/sebastian/.local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/sebastian/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 167, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
(venv) sebastian@sebastian-virtual-machine:~/Documentos/Cyber-Link_GBU_2022/Backend/src$ pip3 install mysqlclient



https://stackoverflow.com/questions/53024891/modulenotfounderror-no-module-named-mysqldb
https://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface
https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-20-04-es